version: '3'

services:
  nginx:
    image: nginx:1.11
    ports: 
      - 27:80   
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./nginx/src:/data/nginx/

  apache:
    build:  ./apache
    ports: 
      - 28:80 
    volumes:
      - ./apache/src:/var/www/html
      - ./apache/000-default.conf:/etc/apache2/sites-available/000-default.conf

  db:
    image: mysql
    volumes:
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    command: mysqld --init-file="/docker-entrypoint-initdb.d/init.sql"
    environment: 
      MYSQL_ROOT_PASSWORD: password
    